//Nome: Gabriel Henrique de Almeida Souza -  RA:2504162

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Restaurante;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CardapioNaoAlcoolico extends javax.swing.JFrame {

    private static CardapioNaoAlcoolico cpnaUnic;
    
    public CardapioNaoAlcoolico() {
        initComponents();
        setLocationRelativeTo( null );
        setDefaultCloseOperation(CardapioNaoAlcoolico.DISPOSE_ON_CLOSE);
        listTab();
    }

    //Singleton
    public static CardapioNaoAlcoolico geraCardapioNaoAlcoolico(){
        if(cpnaUnic == null){
            cpnaUnic = new CardapioNaoAlcoolico();
        }
        return cpnaUnic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCardapio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCardapioNaoAlcoolico = new javax.swing.JTable();
        btProx = new javax.swing.JButton();
        btPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCardapio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbCardapio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCardapio.setText("CARDÁPIO");

        tbCardapioNaoAlcoolico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nº", "Bebida", "ml", "Preco"
            }
        ));
        jScrollPane1.setViewportView(tbCardapioNaoAlcoolico);

        btProx.setText("PRÓXIMO");
        btProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProxActionPerformed(evt);
            }
        });

        btPedido.setText("FAZER PEDIDO");
        btPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btPedido)
                    .addComponent(lbCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btProx)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbCardapio)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btProx)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProxActionPerformed
        CardapioPrato.geraCardapioPrato().setVisible(true);
        dispose();
    }//GEN-LAST:event_btProxActionPerformed

    private void btPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidoActionPerformed
       try {
        // Pergunta ao usuário qual item ele deseja cadastrar
        String numeroItemStr = JOptionPane.showInputDialog(
            null,
            "Digite o número do item que deseja cadastrar:",
            "Cadastro de Item",
            JOptionPane.QUESTION_MESSAGE
        );

        if (numeroItemStr != null) {
            int numeroItem = Integer.parseInt(numeroItemStr);

            // Recupera o nome e preço do item com base no número
            DefaultTableModel modelo = (DefaultTableModel)tbCardapioNaoAlcoolico.getModel();
            if (numeroItem >= 1 && numeroItem <= modelo.getRowCount()) {
                String nomeItem = (String)modelo.getValueAt(numeroItem - 1, 1);
                float precoItem = (float)modelo.getValueAt(numeroItem - 1, 3);
                GerItemPedido gerItemPedido = GerItemPedido.geraItemPedido();
                gerItemPedido.insItemPedido(nomeItem, precoItem);

                JOptionPane.showMessageDialog(
                    null,
                    "Item " + nomeItem + " adicionado ao pedido com sucesso!",
                    "Pedido",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    null,
                    "Número de item inválido. Tente novamente.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
            null,
            "Por favor, insira um número válido.",
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
    } catch (Exception e) {
        JOptionPane.showMessageDialog(
            null,
            "Ocorreu um erro ao processar o pedido.",
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
        e.printStackTrace(); // Pode ser removido em produção.
    }
    }//GEN-LAST:event_btPedidoActionPerformed

     public void listTab(){
        DefaultTableModel modelo = (DefaultTableModel)tbCardapioNaoAlcoolico.getModel();
        int posLin = 0;
        int count=0;
        modelo.setRowCount(posLin);
        GerNaoAlcoolico gerNaoAlcoolico = GerNaoAlcoolico.geraGerNaoAlc();
        for(NaoAlcoolico na1 : gerNaoAlcoolico.getbdNaoAlcoolico()){
            modelo.insertRow(posLin, new Object[]{count+1,na1.getNome(), na1.getVolume(), na1.getPreco()});
            posLin++;
            count++;
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardapioNaoAlcoolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardapioNaoAlcoolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardapioNaoAlcoolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardapioNaoAlcoolico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardapioNaoAlcoolico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPedido;
    private javax.swing.JButton btProx;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCardapio;
    private javax.swing.JTable tbCardapioNaoAlcoolico;
    // End of variables declaration//GEN-END:variables
}
